export const productdata = [
  {
    id: 1,
    name: "Almond Toe Court Shoes, Patent Black",
    category: "Womens Footwear",
    price: 99.0,
    size: ["XS", "S", "M", "M/L"],
    stock: [2, 1, 1, 1],
    amount: 1,
  },
  {
    id: 2,
    name: "Suede Shoes, Blue",
    category: "Womens Footwear",
    price: 42.0,
    size: ["XS", "S", "M", "L"],
    stock: [2, 1, 0, 1],
    amount: 1,
  },
  {
    id: 3,
    name: "Leather Driver Saddle Loafers, Tan",
    category: "Mens Footwear",
    price: 34.0,
    size: ["XS", "S", "M", "L", "XL", "XXL"],
    stock: [3, 2, 2, 2, 2, 1],
    amount: 1,
  },
  {
    id: 4,
    name: "Flip Flops, Red",
    category: "Mens Footwear",
    price: 19.0,
    size: ["XS", "S", "M"],
    stock: [0, 0, 0],
    amount: 1,
  },
  {
    id: 5,
    name: "Flip Flops, Blue",
    category: "Mens Footwear",
    price: 19.0,
    size: ["S", "M", "L"],
    stock: [0, 0, 0],
    amount: 1,
  },
  {
    id: 6,
    name: "Gold Button Cardigan, Black",
    category: "Womens Casualwear",
    price: 167.0,
    size: ["XS", "S", "M", "L"],
    stock: [2, 2, 1, 1],
    amount: 1,
  },
  {
    id: 7,
    name: "Cotton Shorts, Medium Red",
    category: "Womens Casualwear",
    price: 30.0,
    size: ["XS", "S", "M", "L"],
    stock: [1, 1, 2, 1],
    amount: 1,
  },
  {
    id: 8,
    name: "Fine Stripe Short Sleeve Shirt, Grey",
    category: "Mens Casualwear",
    price: 49.99,
    size: ["XS", "S", "M", "L", "XL"],
    stock: [1, 2, 2, 2, 2],
    amount: 1,
  },
  {
    id: 9,
    name: "Fine Stripe Short Sleeve Shirt, Green",
    category: "Mens Casualwear",
    price: 49.99,
    offer: 39.99,
    size: ["XS", "S", "M", "L", "XL"],
    stock: [1, 2, 2, 2, 2],
    amount: 1,
  },
  {
    id: 10,
    name: "Sharkskin Waistcoat, Charcoal",
    category: "Mens Formalwear",
    price: 75.0,
    size: ["S", "M"],
    stock: [0, 2],
    amount: 1,
  },
  {
    id: 11,
    name: "Lightweight Patch Pocket Blazer, Deer",
    category: "Mens Formalwear",
    price: 175.5,
    size: ["M", "L", "XL"],
    stock: [0, 0, 1],
    amount: 1,
  },
];
